use clap::{Command, Arg, ArgAction};

pub fn cmd() -> Command {
    Command::new("idl")
        .about("Interface Definition Language (IDL) tools for ROS 2")
        .aliases(&["interface-def"])
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("protobuf")
            .about("Bidirectional conversion between Protobuf (.proto) and ROS 2 (.msg) files")
            .aliases(["proto", "pb"])
            .arg_required_else_help(true)
            .arg(
                Arg::new("proto_files")
                .help("Input files to convert (.proto or .msg)")
                .required(true)
                .num_args(1..)
                .value_name("INPUT_FILES")
            )
            .arg(
                Arg::new("output_dir")
                .short('o')
                .long("output")
                .value_name("OUTPUT_DIR")
                .help("Output directory for generated files (default: same directory as input files)")
                .default_value(".")
            )
            .arg(
                Arg::new("package_name")
                .short('p')
                .long("package")
                .value_name("PACKAGE_NAME")
                .help("Package name for generated files (default: derived from input)")
                .required(false)
            )
            .arg(
                Arg::new("config_file")
                .short('c')
                .long("config")
                .value_name("CONFIG_FILE")
                .help("Configuration file for type mappings (YAML)")
                .required(false)
            )
            .arg(
                Arg::new("include_dirs")
                .short('I')
                .long("include")
                .value_name("INCLUDE_DIRS")
                .help("Include directories for protobuf imports")
                .num_args(0..)
                .action(ArgAction::Append)
            )
            .arg(
                Arg::new("verbose")
                .short('v')
                .long("verbose")
                .help("Show verbose output")
                .action(ArgAction::SetTrue)
            )
            .arg(
                Arg::new("dry_run")
                .short('n')
                .long("dry-run")
                .help("Show what would be generated without writing files")
                .action(ArgAction::SetTrue)
            )
        )
        .subcommand(
            Command::new("ros2msg")
            .about("Generate Protobuf (.proto) files from ROS 2 messages (.msg)")
            .aliases(["msg", "ros2"])
            .arg_required_else_help(true)
            .arg(
                Arg::new("msg_files")
                .help("ROS 2 message (.msg) files to convert")
                .required(true)
                .num_args(1..)
                .value_name("MSG_FILES")
            )
            .arg(
                Arg::new("output_dir")
                .short('o')
                .long("output")
                .value_name("OUTPUT_DIR")
                .help("Output directory for generated .proto files (default: same directory as .msg files)")
                .default_value(".")
            )
            .arg(
                Arg::new("package_name")
                .short('p')
                .long("package")
                .value_name("PACKAGE_NAME")
                .help("Protobuf package name for generated messages (default: derived from path)")
                .required(false)
            )
            .arg(
                Arg::new("verbose")
                .short('v')
                .long("verbose")
                .help("Show verbose output")
                .action(ArgAction::SetTrue)
            )
            .arg(
                Arg::new("dry_run")
                .short('n')
                .long("dry-run")
                .help("Show what would be generated without writing files")
                .action(ArgAction::SetTrue)
            )
        )
}