use clap::{arg, Command};

pub fn cmd() -> Command {
    Command::new("work")
        .about("Various workspace subcommands")
        .aliases(&["w", "pkg", "pack"])
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("create")
            .about("Create a new package")
            .aliases(["c", "new"])
            .arg_required_else_help(true)
            .arg(
                arg!(<PACKAGE_NAME> "Name of the ROS package to create (e.g. 'demo_nodes_cpp')")
                .required(true)
            )
            .arg(arg!(--package_format <PACKAGE_FORMAT> "The package.xml format."))
            .arg(arg!(--description <DESCRIPTION> "The description given in the package.xml"))
            .arg(arg!(--license <LICENSE> "The license attached to this package"))
            .arg(arg!(--destination_directory <DESTINATION_DIRECTORY> "Directory where to create the package directory"))
            .arg(arg!(--build_type <BUILD_TYPE> "The build type to process the package with"))
            .arg(arg!(--dependencies <DEPENDENCIES>... "List of dependencies"))
            .arg(arg!(--maintainer_email <MAINTAINER_EMAIL> "Email address of the maintainer of this package"))
            .arg(arg!(--maintainer_name <MAINTAINER_NAME> "Name of the maintainer of this package"))
            .arg(arg!(--node_name <NODE_NAME> "Name of the empty executable"))
            .arg(arg!(--library_name <LIBRARY_NAME> "Name of the empty library"))
        )
        .subcommand(
            Command::new("list")
            .about("List all packages")
            .aliases(["l", "ls"])
            .arg(arg!(-a --all "Display all packages even hidden ones"))
            .arg(arg!(-c --count_packages "Only display the number of packages discovered"))
        )
        .subcommand(
            Command::new("info")
            .about("Print information about a package")
            .aliases(["i", "show"])
            .arg(
                arg!(<PACKAGE_NAME> "Name of the ROS package to get info (e.g. 'demo_nodes_cpp')")
                .required(true)
            )
            .arg(arg!(--xml "Output the XML of the package manifest"))
        )
        .subcommand(
            Command::new("build")
            .about("Build packages in the workspace")
            .aliases(["b", "make", "m"])
            .arg(arg!(--base_paths <BASE_PATHS>... "Base paths for package discovery"))
            .arg(arg!(--packages_select <PACKAGES>... "Build only selected packages"))
            .arg(arg!(--packages_ignore <PACKAGES>... "Ignore selected packages"))
            .arg(arg!(--packages_up_to <PACKAGES>... "Build packages up to and including specified packages"))
            .arg(arg!(--parallel_workers <N> "Number of parallel build workers").value_parser(clap::value_parser!(u32)))
            .arg(arg!(--merge_install "Merge install spaces instead of isolated installs"))
            .arg(arg!(--symlink_install "Use symlinks for install (faster development builds)"))
            .arg(arg!(--cmake_args <ARGS>... "Arguments to pass to CMake"))
            .arg(arg!(--cmake_target <TARGET> "Build a specific CMake target"))
            .arg(arg!(--continue_on_error "Continue building other packages when a package fails"))
            .arg(arg!(--event_handlers <HANDLERS>... "Event handlers for build output"))
            .arg(arg!(--executor <EXECUTOR> "Executor type for parallel builds"))
        )
}