use clap::{Arg, Command, arg};

pub fn cmd() -> Command {
    Command::new("work")
        .about("Various workspace subcommands")
        .aliases(&["w", "pkg", "pack"])
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("create")
            .about("Create a new package")
            .aliases(["c", "new"])
            .arg_required_else_help(true)
            .arg(
                arg!(<PACKAGE_NAME> "Name of the ROS package to create (e.g. 'demo_nodes_cpp')")
                .required(true)
            )
            .arg(arg!(--package_format <PACKAGE_FORMAT> "The package.xml format."))
            .arg(arg!(--description <DESCRIPTION> "The description given in the package.xml"))
            .arg(arg!(--license <LICENSE> "The license attached to this package"))
            .arg(arg!(--destination_directory <DESTINATION_DIRECTORY> "Directory where to create the package directory"))
            .arg(arg!(--build_type <BUILD_TYPE> "The build type to process the package with"))
            .arg(arg!(--dependencies <DEPENDENCIES>... "List of dependencies"))
            .arg(arg!(--maintainer_email <MAINTAINER_EMAIL> "Email address of the maintainer of this package"))
            .arg(arg!(--maintainer_name <MAINTAINER_NAME> "Name of the maintainer of this package"))
            .arg(arg!(--node_name <NODE_NAME> "Name of the empty executable"))
            .arg(arg!(--library_name <LIBRARY_NAME> "Name of the empty library"))
        )
        .subcommand(
            Command::new("list")
            .about("List all packages")
            .aliases(["l", "ls"])
            .arg(arg!(-a --all "Display all packages even hidden ones"))
            .arg(arg!(-c --count_packages "Only display the number of packages discovered"))
        )
        .subcommand(
            Command::new("info")
            .about("Print information about a package")
            .aliases(["i", "show"])
            .arg(
                arg!(<PACKAGE_NAME> "Name of the ROS package to get info (e.g. 'demo_nodes_cpp')")
                .required(true)
            )
            .arg(arg!(--xml "Output the XML of the package manifest"))
        )
        .subcommand(
            Command::new("build")
            .about("Build packages in the workspace")
            .aliases(["b", "make", "m"])
            .arg(
                Arg::new("base_paths")
                    .long("base-paths")
                    .visible_alias("base_paths")
                    .num_args(1..)
                    .value_name("BASE_PATHS")
                    .help("Base paths for package discovery")
            )
            .arg(
                Arg::new("build_base")
                    .long("build-base")
                    .visible_alias("build_base")
                    .value_name("BUILD_BASE")
                    .help("Base path for build artifacts")
            )
            .arg(
                Arg::new("install_base")
                    .long("install-base")
                    .visible_alias("install_base")
                    .value_name("INSTALL_BASE")
                    .help("Base path for install artifacts")
            )
            .arg(
                Arg::new("log_base")
                    .long("log-base")
                    .visible_alias("log_base")
                    .value_name("LOG_BASE")
                    .help("Base path for build logs")
            )
            .arg(
                Arg::new("packages_select")
                    .long("packages-select")
                    .visible_alias("packages_select")
                    .num_args(1..)
                    .value_name("PACKAGES")
                    .help("Build only selected packages")
            )
            .arg(
                Arg::new("packages_ignore")
                    .long("packages-ignore")
                    .long("packages-skip")
                    .visible_alias("packages_ignore")
                    .num_args(1..)
                    .value_name("PACKAGES")
                    .help("Ignore selected packages")
            )
            .arg(
                Arg::new("packages_up_to")
                    .long("packages-up-to")
                    .visible_alias("packages_up_to")
                    .num_args(1..)
                    .value_name("PACKAGES")
                    .help("Build packages up to and including specified packages")
            )
            .arg(
                Arg::new("packages_select_build_failed")
                    .long("packages-select-build-failed")
                    .conflicts_with("packages_skip_build_finished")
                    .action(clap::ArgAction::SetTrue)
                    .help("Select packages which failed to build in the previous run")
            )
            .arg(
                Arg::new("packages_select_build_finished")
                    .long("packages-select-build-finished")
                    .conflicts_with("packages_skip_build_failed")
                    .action(clap::ArgAction::SetTrue)
                    .help("Select packages which finished building in the previous run")
            )
            .arg(
                Arg::new("packages_skip_build_finished")
                    .long("packages-skip-build-finished")
                    .conflicts_with("packages_select_build_failed")
                    .action(clap::ArgAction::SetTrue)
                    .help("Skip packages which finished building in the previous run")
            )
            .arg(
                Arg::new("packages_skip_build_failed")
                    .long("packages-skip-build-failed")
                    .conflicts_with("packages_select_build_finished")
                    .action(clap::ArgAction::SetTrue)
                    .help("Skip packages which failed to build in the previous run")
            )
            .arg(
                Arg::new("parallel_workers")
                    .long("parallel-workers")
                    .visible_alias("parallel_workers")
                    .value_name("N")
                    .value_parser(clap::value_parser!(u32))
                    .help("Number of parallel build workers")
            )
            .arg(
                Arg::new("merge_install")
                    .long("merge-install")
                    .visible_alias("merge_install")
                    .action(clap::ArgAction::SetTrue)
                    .help("Merge install spaces instead of isolated installs")
            )
            .arg(
                Arg::new("symlink_install")
                    .long("symlink-install")
                    .visible_alias("symlink_install")
                    .action(clap::ArgAction::SetTrue)
                    .help("Use symlinks for install (faster development builds)")
            )
            .arg(
                Arg::new("cmake_args")
                    .long("cmake-args")
                    .visible_alias("cmake_args")
                    .num_args(1..)
                    .value_name("ARGS")
                    .help("Arguments to pass to CMake")
            )
            .arg(
                Arg::new("cmake_target")
                    .long("cmake-target")
                    .visible_alias("cmake_target")
                    .value_name("TARGET")
                    .help("Build a specific CMake target")
            )
            .arg(
                Arg::new("continue_on_error")
                    .long("continue-on-error")
                    .visible_alias("continue_on_error")
                    .action(clap::ArgAction::SetTrue)
                    .help("Continue building other packages when a package fails")
            )
            .arg(
                Arg::new("event_handlers")
                    .long("event-handlers")
                    .visible_alias("event_handlers")
                    .num_args(1..)
                    .value_name("HANDLERS")
                    .help("Event handlers for build output")
            )
            .arg(
                Arg::new("executor")
                    .long("executor")
                    .value_name("EXECUTOR")
                    .help("Executor type for parallel builds")
            )
        )
        .subcommand(
            Command::new("test")
            .about("Run tests for packages in the workspace")
            .aliases(["t"])
            .arg(
                Arg::new("base_paths")
                    .long("base-paths")
                    .visible_alias("base_paths")
                    .num_args(1..)
                    .value_name("BASE_PATHS")
                    .help("Base paths for package discovery")
            )
            .arg(
                Arg::new("build_base")
                    .long("build-base")
                    .visible_alias("build_base")
                    .value_name("BUILD_BASE")
                    .help("Base path for build artifacts")
            )
            .arg(
                Arg::new("install_base")
                    .long("install-base")
                    .visible_alias("install_base")
                    .value_name("INSTALL_BASE")
                    .help("Base path for install artifacts")
            )
            .arg(
                Arg::new("log_base")
                    .long("log-base")
                    .visible_alias("log_base")
                    .value_name("LOG_BASE")
                    .help("Base path for test logs")
            )
            .arg(
                Arg::new("packages_select")
                    .long("packages-select")
                    .visible_alias("packages_select")
                    .num_args(1..)
                    .value_name("PACKAGES")
                    .help("Test only selected packages")
            )
            .arg(
                Arg::new("packages_ignore")
                    .long("packages-ignore")
                    .long("packages-skip")
                    .visible_alias("packages_ignore")
                    .num_args(1..)
                    .value_name("PACKAGES")
                    .help("Ignore selected packages")
            )
            .arg(
                Arg::new("packages_up_to")
                    .long("packages-up-to")
                    .visible_alias("packages_up_to")
                    .num_args(1..)
                    .value_name("PACKAGES")
                    .help("Test packages up to and including specified packages")
            )
            .arg(
                Arg::new("merge_install")
                    .long("merge-install")
                    .visible_alias("merge_install")
                    .action(clap::ArgAction::SetTrue)
                    .help("Treat the workspace as using merged install layout")
            )
            .arg(
                Arg::new("continue_on_error")
                    .long("continue-on-error")
                    .visible_alias("continue_on_error")
                    .action(clap::ArgAction::SetTrue)
                    .help("Continue testing other packages when a package test fails")
            )
            .arg(
                Arg::new("ctest_args")
                    .long("ctest-args")
                    .visible_alias("ctest_args")
                    .num_args(1..)
                    .allow_hyphen_values(true)
                    .value_name("ARGS")
                    .help("Arguments to pass to ctest for CMake packages")
            )
            .arg(
                Arg::new("pytest_args")
                    .long("pytest-args")
                    .visible_alias("pytest_args")
                    .num_args(1..)
                    .allow_hyphen_values(true)
                    .value_name("ARGS")
                    .help("Arguments to pass to pytest for Python packages")
            )
        )
}
